name: Build breach candidates & JSON

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Prepare folders
        run: |
          mkdir -p out

      - name: Scrape sources -> corpus.jsonl
        run: python tools/scrape_sources.py

      - name: Build candidates
        run: python tools/build_candidates.py

      - name: Export Breach-ui JSON
        run: python tools/export_breach_ui_json.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: courtfirst-out
          path: |
            out/corpus.jsonl
            out/breach_candidates.json
            out/breaches.json
