name: Enrich first 10 cases (preview + heartbeat)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  enrich:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo (CourtFirst)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Sanity check input exists
        run: |
          test -f data/cases.csv || (echo "data/cases.csv not found" && exit 1)
          head -n 5 data/cases.csv || true

      - name: Run first-10 enrichment (heartbeat enabled)
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
        run: |
          python tools/enrich_first10.py \
            --input data/cases.csv \
            --outdir out/preview-enrichment \
            --limit 10 \
            --abort-after 6 \
            --sleep-min 1.6 \
            --sleep-max 2.6

      - name: Upload preview artifacts (unique name)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: preview-enrichment-${{ github.run_id }}-${{ github.run_attempt }}
          path: out/preview-enrichment/**
          if-no-files-found: error
          retention-days: 14
