name: Enrich first N cases (preview + heartbeat)

on:
  workflow_dispatch:
    inputs:
      start:
        description: "Start row (0-based)"
        required: false
        default: "0"
      limit:
        description: "How many rows to process"
        required: false
        default: "10"

permissions:
  contents: read

jobs:
  enrich:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo (CourtFirst)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Sanity check input exists
        run: |
          test -f data/cases.csv || (echo "data/cases.csv not found" && exit 1)
          head -n 5 data/cases.csv || true

      - name: Run enrichment preview (heartbeat enabled)
        run: |
          mkdir -p out/preview-enrichment
          python tools/enrich_first10.py \
            --input data/cases.csv \
            --outdir out/preview-enrichment \
            --start "${{ inputs.start }}" \
            --limit "${{ inputs.limit }}" \
            --sleep-min 0.0 --sleep-max 0.0 --abort-after 8

      - name: Upload preview artifacts
        uses: actions/upload-artifact@v4
        with:
          name: preview-enrichment
          path: |
            out/preview-enrichment/cases_preview.csv
            out/preview-enrichment/urls_preview.json
            out/preview-enrichment/skipped_preview.json
