name: Enrich cases with source URLs

on:
  workflow_dispatch:
    inputs:
      cases_path:
        description: "Path to cases.csv (case_id,jurisdiction,title,year,source_url)"
        required: false
        default: "data/cases.csv"
      min_score:
        description: "Min fuzzy score (0-100) to accept a match"
        required: false
        default: "86"
      max_results_per_site:
        description: "Max results to consider per site"
        required: false
        default: "10"

jobs:
  enrich:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out CourtFirst
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 rapidfuzz

      - name: Enrich URLs (search-only)
        run: |
          mkdir -p out
          python tools/enrich_urls.py \
            --cases "${{ github.event.inputs.cases_path }}" \
            --out out/cases_enriched.csv \
            --min-score ${{ github.event.inputs.min_score }} \
            --max-results-per-site ${{ github.event.inputs.max_results_per_site }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cases_enriched_csv
          path: out/cases_enriched.csv
