name: Enrich cases with sources

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out CourtFirst
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Resolve source URLs (JerseyLaw / BAILII)
        run: |
          python tools/enrich_sources.py

      - name: Fetch HTML
        run: |
          python tools/fetch_cases.py

      - name: Parse metadata
        run: |
          python tools/parse_cases.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: courtfirst-enriched
          path: |
            out/sources.json
            out/fetched.json
            out/cases_enriched.json
            out/html
