name: Enrich first N cases (preview + heartbeat)

on:
  workflow_dispatch:
    inputs:
      start:
        description: "Row to start from (0-based)"
        required: false
        default: "0"
      limit:
        description: "How many rows to preview/enrich"
        required: false
        default: "10"

permissions:
  contents: read

jobs:
  enrich:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo (CourtFirst)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (requests, bs4, lxml, ddg)
        run: |
          python -V
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml duckduckgo-search

      - name: Sanity check input exists
        run: |
          test -f data/cases.csv || (echo "data/cases.csv not found" && exit 1)
          head -n 5 data/cases.csv || true

      - name: Run enrichment preview (heartbeat enabled)
        env:
          START: ${{ github.event.inputs.start }}
          LIMIT: ${{ github.event.inputs.limit }}
        run: |
          mkdir -p out/preview-enrichment
          python tools/enrich_first10.py \
            --start "${START:-0}" \
            --limit "${LIMIT:-10}" \
            --outdir out/preview-enrichment \
            --sleep-min 2.0 --sleep-max 3.5 --max-consec-fail 8

      - name: Upload preview artifacts
        uses: actions/upload-artifact@v4
        with:
          name: preview-enrichment
          path: |
            out/preview-enrichment/cases_preview.csv
            out/preview-enrichment/urls_preview.json
            out/preview-enrichment/skipped_preview.json
          if-no-files-found: warn
