name: Enrich first 10 cases (preview + heartbeat)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  enrich:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo (CourtFirst)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Sanity check input exists
        run: |
          test -f data/cases.csv || (echo "data/cases.csv not found" && exit 1)
          mkdir -p out/preview-enrichment

      # IMPORTANT: only use the args that enrich_first10.py actually supports.
      # Positional LIMIT = 10, --out for output path, and --abort-after for early exit.
      - name: Run first-10 enrichment (heartbeat enabled)
        run: |
          python tools/enrich_first10.py 10 \
            --out out/preview-enrichment/results.json \
            --abort-after 8

      - name: Upload preview artifacts
        uses: actions/upload-artifact@v4
        with:
          name: preview-enrichment
          path: |
            out/preview-enrichment/**
          if-no-files-found: warn
