name: Enrich URLs for cases (batched, polite)

on:
  workflow_dispatch:

jobs:
  enrich:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Load row count
        id: count
        shell: bash
        run: |
          ROWS=$(python - << 'PY'
import csv
import sys
with open("data/cases.csv", newline="", encoding="utf-8") as f:
    print(sum(1 for _ in csv.reader(f)) - 1)
PY
)
          echo "rows=$ROWS" >> $GITHUB_OUTPUT

      - name: Compute batches (chunks of ~400)
        id: batches
        shell: bash
        run: |
          ROWS=${{ steps.count.outputs.rows }}
          SIZE=400
          STARTS=()
          ENDS=()
          i=0
          while [ $i -lt $ROWS ]; do
            STARTS+=($i)
            j=$(( i + SIZE ))
            if [ $j -gt $ROWS ]; then j=$ROWS; fi
            ENDS+=($j)
            i=$j
          done
          echo "starts=${STARTS[*]}" >> $GITHUB_OUTPUT
          echo "ends=${ENDS[*]}" >> $GITHUB_OUTPUT

      - name: Run enrichment batches
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t STARTS < <(echo "${{ steps.batches.outputs.starts }}")
          mapfile -t ENDS   < <(echo "${{ steps.batches.outputs.ends }}")
          for idx in "${!STARTS[@]}"; do
            S=${STARTS[$idx]}
            E=${ENDS[$idx]}
            echo ""
            echo "=== Batch $((idx+1))/${#STARTS[@]} :: rows $S..$E ==="
            python tools/enrich_urls.py \
              --input data/cases.csv \
              --out data/cases.csv \
              --start "$S" --end "$E" \
              --sleep-min 2.0 --sleep-max 4.0 \
              --emit-json --batch-name "batch-$((idx+1))"
          done

      - name: Upload artifacts (CSV + reports)
        uses: actions/upload-artifact@v4
        with:
          name: enriched-cases
          path: |
            data/cases.csv
            out/preview-enrichment/*
