name: Extract cases from LTJ lines

on:
  workflow_dispatch:
    inputs:
      start:
        description: "Start line (inclusive) in LTJ.lines.json"
        required: true
        default: "1276"
      end:
        description: "End line (inclusive) in LTJ.lines.json"
        required: true
        default: "3083"
      ltj_ref:
        description: "LTJ-ui ref (branch/tag/sha)"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out CourtFirst
        uses: actions/checkout@v4

      - name: Check out LTJ-ui (private, read-only)
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.LTJ_REPO }}
          ref: ${{ github.event.inputs.ltj_ref }}
          path: LTJ-ui
          token: ${{ secrets.LTJ_READ_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip

      - name: Extract lines -> data/cases.csv (merge)
        run: |
          python tools/extract_cases_from_lines.py \
            --ltj-lines LTJ-ui/out/LTJ.lines.json \
            --start "${{ github.event.inputs.start }}" \
            --end   "${{ github.event.inputs.end }}" \
            --out   data/cases.csv \
            --merge

      - name: Commit results into CourtFirst
        run: |
          git config user.name  "courtfirst-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/cases.csv
          git commit -m "Update cases.csv from LTJ lines ${{ github.event.inputs.start }}–${{ github.event.inputs.end }}" || echo "No changes"
          git push
