name: Extract cases from LTJ lines

on:
  workflow_dispatch:
    inputs:
      start:
        description: "Start line (inclusive) in LTJ.lines.json"
        required: true
        default: "1276"
      end:
        description: "End line (inclusive) in LTJ.lines.json"
        required: true
        default: "3083"
      ltj_ref:
        description: "LTJ-ui ref (branch/tag/sha)"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out CourtFirst
        uses: actions/checkout@v4

      - name: Check out LTJ-ui (private, read-only)
        uses: actions/checkout@v4
        with:
          repository: Info1691/LTJ-ui
          ref: ${{ github.event.inputs.ltj_ref }}
          token: ${{ secrets.LTJ_UI_TOKEN }}
          path: LTJ-ui

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip

      - name: Extract case lines (filters numeric/page indexes)
        run: |
          python tools/extract_cases_from_lines.py \
            --ltj-lines LTJ-ui/out/LTJ.lines.json \
            --start "${{ github.event.inputs.start }}" \
            --end "${{ github.event.inputs.end }}" \
            --out data/cases.csv \
            --merge \
            --report out/extract_report.json

      - name: Upload extract report
        uses: actions/upload-artifact@v4
        with:
          name: extract-report
          path: |
            out/extract_report.json
            data/cases.csv
