name: Extract + Clean + Enrich (LTJ)

on:
  workflow_dispatch:
    inputs:
      ltj_lines_path:
        description: 'Path to LTJ-ui/out/LTJ.lines.json'
        required: false
        default: 'LTJ-ui/out/LTJ.lines.json'
      start_line:
        description: 'Start line (inclusive)'
        required: true
        default: '1276'
      end_line:
        description: 'End line (inclusive)'
        required: true
        default: '3083'
      max_cases:
        description: 'Cap for debug (0 = no cap)'
        required: false
        default: '0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out CourtFirst
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check out LTJ-ui (private)
        uses: actions/checkout@v4
        with:
          repository: Info1691/LTJ-ui
          path: LTJ-ui
          token: ${{ secrets.LTJ_UI_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-slugify

      - name: Prepare folders
        run: |
          mkdir -p data out

      - name: Extract cases (ALL)
        run: |
          python tools/extract_cases_from_ltj.py \
            --ltj-lines "${{ github.event.inputs.ltj_lines_path }}" \
            --start ${{ github.event.inputs.start_line }} \
            --end ${{ github.event.inputs.end_line }} \
            --out data/cases_raw.csv \
            --max ${{ github.event.inputs.max_cases }}

      - name: Clean titles safely (no drops)
        run: |
          python tools/clean_cases.py \
            --inp data/cases_raw.csv \
            --out data/cases_clean.csv \
            --report out/clean_report.json

      - name: Enrich with real URLs (JerseyLaw → BAILII → DDG)
        run: |
          python tools/enrich_sources.py \
            --inp data/cases_clean.csv \
            --out data/cases.csv \
            --report out/enrich_report.json \
            --limit 0

      - name: Upload artifacts (CSV + reports)
        uses: actions/upload-artifact@v4
        with:
          name: cases-and-reports
          path: |
            data/cases_raw.csv
            data/cases_clean.csv
            data/cases.csv
            out/clean_report.json
            out/enrich_report.json
