name: Extract Cases from LTJ.lines.json

on:
  workflow_dispatch:
  push:
    paths:
      - 'tools/extract_cases_from_lines.py'
      - 'LTJ-ui/out/LTJ.lines.json'

jobs:
  extract:
    name: Build cases.csv from LTJ.lines.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run extraction script
        run: |
          python tools/extract_cases_from_lines.py \
            --input LTJ-ui/out/LTJ.lines.json \
            --out data/cases.csv \
            --skip-report data/skip_report.json \
            --start-line 1276 --end-line 3083

      - name: Upload artifacts (cases.csv + skip report)
        uses: actions/upload-artifact@v4    # ✅ UPDATED HERE
        with:
          name: extracted-cases
          path: |
            data/cases.csv
            data/skip_report.json
