name: Extract + Clean + Enrich (LTJ)

on:
  workflow_dispatch:
    inputs:
      ltj_ref:
        description: "LTJ-ui ref (branch/tag/SHA)"
        default: "main"
        required: true
      start_line:
        description: "Start line (inclusive) in LTJ.lines.json"
        default: "1276"
        required: true
      end_line:
        description: "End line (inclusive) in LTJ.lines.json"
        default: "3083"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out CourtFirst
        uses: actions/checkout@v4

      - name: Check out LTJ-ui (private)
        uses: actions/checkout@v4
        with:
          repository: Info1691/LTJ-ui
          ref: ${{ inputs.ltj_ref }}
          token: ${{ secrets.LTJ_UI_TOKEN }}
          path: LTJ-ui

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install duckduckgo-search==6.2.10 requests beautifulsoup4

      - name: Prepare folders
        run: mkdir -p data out

      - name: Extract cases (ALL or bounded range)
        env:
          LTJ_LINES: LTJ-ui/out/LTJ.lines.json
          OUT_CSV: out/extracted.csv
          START: ${{ inputs.start_line }}
          END: ${{ inputs.end_line }}
        run: |
          python tools/extract_cases_from_lines.py --lines "$LTJ_LINES" --out "$OUT_CSV" --start "$START" --end "$END"

      - name: Clean titles safely (no drops)
        env:
          IN_CSV: out/extracted.csv
          OUT_CSV: out/clean.csv
        run: |
          python tools/clean_cases.py --input "$IN_CSV" --out "$OUT_CSV"

      - name: Enrich with real URLs (JerseyLaw ➜ BAILII ➜ DDG)
        env:
          IN_CSV: out/clean.csv
          OUT_CSV: data/cases.csv
        run: |
          python tools/enrich_sources.py --input "$IN_CSV" --out "$OUT_CSV"

      - name: Upload artifacts (CSV + reports)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: courtfirst-results
          path: |
            out/**
            data/cases.csv

      - name: Commit updated CSV into CourtFirst
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/cases.csv
          git commit -m "Update cases.csv via Extract+Clean+Enrich" || echo "No changes to commit"
          git push
