name: Extract cases from LTJ lines

on:
  workflow_dispatch:
    inputs:
      start_line:
        description: "Start line (inclusive) in LTJ.lines.json"
        required: false
        default: "1276"
      end_line:
        description: "End line (inclusive) in LTJ.lines.json"
        required: false
        default: "3083"
      ltj_ref:
        description: "LTJ-ui ref (branch/tag/sha)"
        required: false
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out CourtFirst
        uses: actions/checkout@v4

      - name: Check out LTJ-ui (private) read-only
        uses: actions/checkout@v4
        with:
          repository: Info1691/LTJ-ui
          ref: ${{ github.event.inputs.ltj_ref }}
          token: ${{ secrets.LTJ_PAT }}
          path: LTJ-ui

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install rapidfuzz

      - name: Extract cases
        run: |
          mkdir -p out
          python tools/extract_cases.py \
            --lines LTJ-ui/out/LTJ.lines.json \
            --start ${{ github.event.inputs.start_line }} \
            --end   ${{ github.event.inputs.end_line }} \
            --out   out/cases.csv

      - name: Upload artifact (cases.csv)
        uses: actions/upload-artifact@v4
        with:
          name: cases_csv
          path: out/cases.csv
