name: Extract cases from LTJ lines

on:
  workflow_dispatch:
    inputs:
      start_line:
        description: "Start line (inclusive) in LTJ lines"
        required: true
        default: "1276"
      end_line:
        description: "End line (inclusive) in LTJ lines"
        required: true
        default: "3083"
      ltj_ref:
        description: "LTJ-ui ref (branch/tag/SHA)"
        required: true
        default: "main"
      lines_filename:
        description: "File in LTJ-ui/out (LTJ.lines.json or LTK.lines.json)"
        required: true
        default: "LTJ.lines.json"

permissions:
  contents: write

env:
  OUT_CSV: data/cases.csv

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out CourtFirst
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Make data folder
        run: mkdir -p data

      - name: Check out LTJ-ui (private, read-only)
        uses: actions/checkout@v4
        with:
          repository: Info1691/LTJ-ui
          ref: ${{ inputs.ltj_ref }}
          token: ${{ secrets.LTJ_UI_TOKEN }}
          path: ltj

      - name: Verify LTJ lines file exists
        id: lines
        run: |
          set -e
          f="ltj/out/${{ inputs.lines_filename }}"
          echo "file=$f" >> $GITHUB_OUTPUT
          [[ -f "$f" ]] || { echo "::error::Missing $f"; exit 1; }
          echo "Found $f"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Extract and merge
        run: |
          python tools/extract_cases_from_lines.py \
            --lines "${{ steps.lines.outputs.file }}" \
            --start ${{ inputs.start_line }} \
            --end ${{ inputs.end_line }} \
            --out "${{ env.OUT_CSV }}"

      - name: Commit CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Extracted cases from LTJ lines ${{ inputs.start_line }}–${{ inputs.end_line }}"
          file_pattern: data/cases.csv

      - name: Upload CSV (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: cases.csv
          path: data/cases.csv
