name: Extract cases from LTJ lines

on:
  workflow_dispatch:
    inputs:
      start_line:
        description: "Start line (inclusive) in LTJ.lines.json"
        required: true
        default: "1276"
      end_line:
        description: "End line (inclusive) in LTJ.lines.json"
        required: true
        default: "3083"
      ltj_ref:
        description: "LTJ-ui ref (branch/tag/sha)"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to commit back to CourtFirst
    steps:
      - name: Check out CourtFirst (target repo)
        uses: actions/checkout@v4

      - name: Check out LTJ-ui (private) read-only
        uses: actions/checkout@v4
        with:
          repository: Info1691/LTJ-ui
          ref: ${{ inputs.ltj_ref }}
          token: ${{ secrets.LTJ_UI_TOKEN }}
          path: LTJ-ui

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (optional)
        run: |
          python -m pip install --upgrade pip
          # no strict deps required for this script; csv/json only
          true

      - name: Extract lines -> data/cases.csv (merge)
        run: |
          python tools/extract_cases_from_lines.py \
            --ltj-lines "LTJ-ui/out/LTJ.lines.json" \
            --start "${{ inputs.start_line }}" \
            --end "${{ inputs.end_line }}" \
            --out "data/cases.csv" \
            --merge

      - name: Commit results into CourtFirst
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/cases.csv
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Extract LTJ cases lines ${{ inputs.start_line }}–${{ inputs.end_line }} from ${{ inputs.ltj_ref }}"
            git push
          fi
